### ISSUE TITLE
@everyone isnt working properly

### ISSUE THREAD

**Issue by rocketpitah** [MinnDevelopment/strumbot#13]
Hi,

sorry for the second issue.
I would like to inform everyone in Discord now that XY-Streamer has gone online.
I changed the text in en.properties and de.properties and added @everyone everywhere. 
When the notification comes from the bot @everyone is highlighted in blue, but unfortunately no one is notified?
The notifications are then always highlighted in yellow, but this is not.
Is there a workaround there or am I doing something wrong?

best regards

**Comment by MinnDevelopment** [comment]
Everyone mentions are unsupported by design, use notification roles.

If you want to modify the code, you have to change the allowed mentions:

https://github.com/MinnDevelopment/strumbot/blob/709c02c8a3d8b71c2f92e727094dfd2fe78661fb/src/main/kotlin/strumbot/main.kt#L66

Additionally, the `@everyone` role must be allowed to mention everyone in the channel permissions.
